### ISSUE TITLE
Does this plugin work with ELK 5.1 ?

### ISSUE THREAD

**Issue by smene** [skroutz/elasticsearch-skroutz-greekstemmer#17]
How can be installed on ELK 5.1 or later?

**Comment by cmantas** [comment]
Unfortunatelly, this plugin has only ever been tested on ES up to v1.5. 
An update for ESv5 is not planned for the imminent future but will probably happen within 2017.

**Comment by lovemeblender** [comment]
We are pleased to announce that this plugin is now supported on ES 5.4.0!
