### ISSUE TITLE
Φίλε, μήπως μπορείς να μου πεις τι χρειάζεται να κάνω για να το ανανεώσω για ES 6?

### ISSUE THREAD

**Issue by pdiveris** [skroutz/elasticsearch-skroutz-greekstemmer#22]
Φίλε, μήπως μπορείς να μου πεις τι χρειάζεται να κάνω για να το ανανεώσω για ES 6?

**Comment by cmantas** [comment]
Assuming you mean ES5 as ES6 is not coming in the near future.
Unfortunately a stable version of this plugin for ES5 has not been released yet.
That being said, you could try, at your own risk, a development version as found [here](https://github.com/skroutz/elasticsearch-skroutz-greekstemmer/pull/18).

You will need to build it from source and install it from the resulting zip file.

From the plugin's repo, checkout the `elasticsearch_5_1_X` branch and build it (with `mvn package`).
The plugin zip will be under `target/releases`.

Find out the installation dir of ES calling the `_nodes` endpoint. eg:
`curl "localhost:9200/_nodes?pretty=true&settings=true" 2>/dev/null | grep home`
(for debian it's under `usr/share`).

Then use the `plugin` script under the `bin`  dir to install the zip.
```
sudo /usr/share/elasticsearch/bin/plugin --install target/releases/elasticsearch-skroutz-greekstemmer-0.0.13-SNAPSHOT.zip
```
Assuming you mean ES5 as ES6 is not coming in the near future.
Unfortunately a stable version of this plugin for ES5 has not been released yet.
That being said, you could try, at your own risk, a development version as found [here](https://github.com/skroutz/elasticsearch-skroutz-greekstemmer/pull/18).

You will need to build it from source and install it from the resulting zip file.

From the plugin's repo, checkout the `elasticsearch_5_1_X` branch and build it (with `mvn package`).
The plugin zip will be under `target/releases`.

Find out the installation dir of ES calling the `_nodes` endpoint. eg:
`curl "localhost:9200/_nodes?pretty=true&settings=true" 2>/dev/null | grep home`
(for debian it's under `usr/share`).

Then use the `plugin` script under the `bin`  dir to install the zip.
```
sudo /usr/share/elasticsearch/bin/plugin --install target/releases/elasticsearch-skroutz-greekstemmer-0.0.13-SNAPSHOT.zip
```

Closing this Issue as it will not be helpful for other users

**Comment by mixalistzikas** [comment]
any news about ES6?

**Comment by greenonion** [comment]
Nope, we're still using ES5 and will be for the foreseeable future. We're accepting PRs though, it shouldn't be too hard.
