### ISSUE TITLE
elasticsearch 2

### ISSUE THREAD

**Issue by bobosss** [skroutz/elasticsearch-skroutz-greekstemmer#9]
Αποτυχία εγκατάστασης σε elasticsearch 2
ERROR: Could not find plugin descriptor 'plugin-descriptor.properties' in plugin zip

**Comment by chief** [comment]
true
Δεν το έχουμε δοκιμάσει σε ES2.0 ακόμα.

**Comment by bobosss** [comment]
devbox ubuntu 15.10 elasticsearch 2.0 και τα 2 plugin του skroutz dinoun to parapano error...

**Comment by chief** [comment]
thx θα το δοκιμάσουμε σύντομα

**Comment by kvavliak** [comment]
Καλησπέρα, υπάρχει timeline για release compatible με ES 2 ?
Ευχαριστώ εκ των προτέρων :)

**Comment by chief** [comment]
καλησπέρα, 
καταρχάς ένα PR θα ήταν ευπρόσδεκτο :) :) 
αν δεν γίνει όμως αυτο υπολογίζουμε στο επόμενο τετράμηνο περίπου. 
thx

**Comment by lovemeblender** [comment]
Πλεον το ES 2.4.4 υποστηριζεται από το 2.4.4 branch.

**Comment by kvavliak** [comment]
Ευχαριστούμε για την ενημέρωση :)
